video:
  frame_rate: 30  # frames per second to process
  stabilization: true  # enable video stabilization

detection:
  grid:
    # Edge detection parameters
    edge_detection:
      canny_low: 50
      canny_high: 150

    color_threshold: 0.3
    epsilon_factor: 0.02
    
    # Line detection parameters
    hough_threshold: 50
    min_line_length: 100
    max_line_gap: 10
    
    # Grid color detection (HSV)
    grid_color_range:
      lower: [100, 90, 90]   # Blue color lower bound
      upper: [125, 255, 255] # Blue color upper bound
    
    # Grid dimensions
    rows: 6
    cols: 7
    
    # Circle detection for grid cells
    circle_detection:
      min_dist: 10
      param1: 10
      param2: 15
      min_radius: 5
      max_radius: 50
    
    # Counter colors (HSV)
    red_ranges:
      - lower: [0, 120, 70]
        upper: [10, 255, 255]
      - lower: [170, 120, 70]
        upper: [180, 255, 255]
    yellow_range:
      lower: [20, 100, 100]
      upper: [30, 255, 255]
  
  dice:
    edge_detection:
      canny_low: 50
      canny_high: 150
    color_range:
      lower: [0, 0, 230]
      upper: [0, 0, 255] 
    min_radius: 5
    max_radius: 15

output:
  save_annotated_video: true
